### PR TITLE
Add move and bump-attack animations, plus more

### PR DESCRIPTION
**Pull request by tommyettinger**
The assets that aren't currently used have been moved to a folder in the root of the project, where they can be copied back into assets as needed. The font is DejaVu across the project now; if you change the font you need to bring in the .fnt and .png files that go with it from unused_assets.

Various tweaks were made based on VisualVM profiling info, like String.format creating lots of temporary byte[] data, and the resistance map from from Vision is now part of the Map it refers to, so Line_Of_Sight can use it too.

The projects are remade somewhat so a runnable JAR can be built; there's some issues with Gradle 4.x and the older way we made JARs, but it isn't super-clear to me yet how the changes affect this project. Being able to make a JAR is probably a goal of the project, so I hope this works :smile: 

The lockup bug I believe was caused by re-entering a dungeon level and the action being repeated for some reason, which the game wasn't ready to handle. I set the current Action to null if a key is received that isn't known, which at least enables this to be debugged (so you can press F7, F8, F9, etc. without sending those to the game) and also seems to address the bug somehow.

### CODE REVIEW

**Comment by tommyettinger** [comment]
This also gets the goblin to chase correctly.

**Comment by tommyettinger** [comment]
I amended the PR to include your changes from July 11 and my additions of animations for movement and bump-attacks. The player slides pretty smoothly when you hold a key down (I think the energy system causes a slight pause between moves as it finishes handling other actions). Goblins are definitely having some issues with AI, not sure quite what's up but they like to move instead of attacking sometimes. This also includes most but not all of my changes from the previous version of this PR, including moving unused assets to a separate folder so they won't get copied into a 40+ MB jar file.

**Comment by tommyettinger** [comment]
OK, now this PR can be merged. It has the animations working for bump attacks and sliding between tiles; more involved animations will likely use PanelEffect from SquidLib. PanelEffect already has a projectile effect that goes in a line, a few explosions, a "grenade" effect that arcs (changing speed) and chains into an explosion effect, and several others. A PanelEffect is applied by adding one as a Scene2D Action onto a SparseLayers. It should be noted that the SparseLayers used by Game_Screen is now part of EntityManager because we really need access to animation info in lots of places (like how input should wait until animations finish).

**Comment by Knickkennedy** [comment]
Merged successfully. Will look at code base today!

**Pull request merged**
